Added implementation of ignore-missing

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -60,6 +60,16 @@ workdir=${BUILDKITE_PLUGIN_ARTIFACTS_WORKDIR:-.}
 pushd "${workdir}"
 trap popd EXIT
 
+bk_agent() {
+  if ! buildkite-agent artifact "${@}"; then
+    if [[ "${BUILDKITE_PLUGIN_ARTIFACTS_IGNORE_MISSING:-"false"}" != "false" ]]; then
+      echo "Ignoring error in upload"
+    else
+      echo "Error in upload"
+      exit 1
+    fi
+  fi
+}
 
 # Set user-provided object ACL for AWS S3
 if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_S3_UPLOAD_ACL:-}" ]] ; then
@@ -97,7 +107,7 @@ if [[ "${SINGULAR_UPLOAD_OBJECT}" == "true" ]]; then
   fi
 
   echo "~~~ Uploading artifacts ${EXTRA_MESSAGE}"
-  buildkite-agent artifact "${args[@]}" "${path}"
+  bk_agent "${args[@]}" "${path}"
 elif [[ "${COMPRESSED}" == "true" ]]; then
   final_paths=()
   index=0
@@ -120,7 +130,7 @@ elif [[ "${COMPRESSED}" == "true" ]]; then
   "${compress[@]}" "${final_paths[@]}"
 
   echo "~~~ Uploading artifacts ${EXTRA_MESSAGE}"
-  buildkite-agent artifact "${args[@]}" "${BUILDKITE_PLUGIN_ARTIFACTS_COMPRESSED}"
+  bk_agent "${args[@]}" "${BUILDKITE_PLUGIN_ARTIFACTS_COMPRESSED}"
 elif [[ "${MULTIPLE_UPLOADS}" == "true" ]]; then
   index=0
   echo "~~~ Uploading artifacts ${EXTRA_MESSAGE}"
@@ -136,7 +146,7 @@ elif [[ "${MULTIPLE_UPLOADS}" == "true" ]]; then
       path="${!dest_env_var}"
     fi
 
-    buildkite-agent artifact "${args[@]}" "$path"
+    bk_agent "${args[@]}" "$path"
     ((index+=1))
   done
 fi
diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -46,6 +46,17 @@ if [[ "${#paths[@]}" -le 0 ]]; then
   exit 0
 fi
 
+bk_agent() {
+  if ! buildkite-agent artifact "${@}"; then
+    if [[ "${BUILDKITE_PLUGIN_ARTIFACTS_IGNORE_MISSING:-"false"}" != "false" ]]; then
+      echo "Ignoring error in download"
+    else
+      echo "Error in download"
+      exit 1
+    fi
+  fi
+}
+
 if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_COMPRESSED:-}" ]]; then
   COMPRESSED="true"
   if [[ "${BUILDKITE_PLUGIN_ARTIFACTS_COMPRESSED}" =~ .*\.zip ]]; then
@@ -68,8 +79,7 @@ workdir="${BUILDKITE_PLUGIN_ARTIFACTS_WORKDIR:-.}"
 
 if [[ "${COMPRESSED}" == "true" ]]; then
   echo "~~~ Downloading artifacts ${EXTRA_MESSAGE}"
-  buildkite-agent artifact "${args[@]}" "${BUILDKITE_PLUGIN_ARTIFACTS_COMPRESSED}" "${workdir}"
-
+  bk_agent "${args[@]}" "${BUILDKITE_PLUGIN_ARTIFACTS_COMPRESSED}" "${workdir}"
 
   echo "~~~ Uncompressing ${paths[*]} from ${BUILDKITE_PLUGIN_ARTIFACTS_COMPRESSED}"
   "${compress[@]}" "${paths[@]}"
@@ -107,7 +117,7 @@ elif [[ "${SINGULAR_DOWNLOAD_OBJECT}" == "true" ]]; then
   fi
 
   echo "~~~ Downloading artifacts ${EXTRA_MESSAGE}"
-  buildkite-agent artifact "${args[@]}" "${source}" "${workdir}"
+  bk_agent "${args[@]}" "${source}" "${workdir}"
 
   if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO:-}" ]]; then
     if ! [[ -d $(dirname "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO}") ]]; then
@@ -128,7 +138,7 @@ elif [[ "${MULTIPLE_DOWNLOADS}" == "true" ]]; then
     else
       source="${path}"
     fi
-    buildkite-agent artifact "${args[@]}" "${source}" "${workdir}"
+    bk_agent "${args[@]}" "${source}" "${workdir}"
     if [[ -n "${!dest_env_var:-}" ]]; then
       if ! [[ -d $(dirname "${!dest_env_var}") ]]; then
         mkdir -p "$(dirname "${!dest_env_var}")"
